name: Backend

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@sm/one-gh-actions-job-for-all-tests
    with:
      enable_backend_testing: true

      backend_directory: .
